# Generated by Django 6.0.4 on 2026-05-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('Sequedad', 'sequedad'), ('Temperatura incoherente', 'temperatura incoherente'), ('Energía baja', 'energia baja')], max_length=30)),
                ('nivel', models.CharField(choices=[('bajo', 'Baja'), ('medio', 'Media'), ('alto', 'Alta'), ('critico', 'Crítico')], max_length=20)),
                ('descripcion', models.TextField()),
                ('variable_afectada', models.CharField(choices=[('humedad', 'Humedad'), ('temperatura', 'Temperatura'), ('bateria', 'Batería')], editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisada', 'Revisada'), ('descartada', 'Descartada')], default='pendiente', max_length=20)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='alerts.alert')),
            ],
        ),
    ]
