# Generated by Django 5.2.13 on 2026-05-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnviroProRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('humedad_media', models.FloatField()),
                ('temp_suelo', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
                ('bateria', models.FloatField()),
                ('panel_solar', models.FloatField()),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
