# Generated by Django 6.0.4 on 2026-05-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviropro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enviroprorecord',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='enviroprorecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
